import AppKit
import ApplicationServices
import CoreGraphics
import Testing
@testable import NamiStudio

@MainActor private final class PasteEnvironment {
    var allowed = true
    var target: TranscriptPaster.Target? = .init(pid: 42, element: AXUIElementCreateApplication(42))
    var flags: CGEventFlags = []
    var sentTo: [pid_t] = []
    var canPost = true
    var onPost: () -> Void = {}

    func paster(pasteboard: NSPasteboard = .general,
                waitForPaste: @escaping @MainActor () async -> Void = {}) -> TranscriptPaster {
        TranscriptPaster(accessibilityGranted: { self.allowed }, focusedTarget: { self.target },
                         modifiers: { self.flags }, postPaste: {
            self.sentTo.append($0)
            self.onPost()
            return self.canPost
        }, pasteboard: pasteboard, waitForPaste: waitForPaste)
    }
}

@Test @MainActor func pastesOnlyToTheCapturedAppAndField() async {
    let environment = PasteEnvironment()
    let paste = environment.paster().prepare()
    #expect(environment.sentTo.isEmpty)
    #expect(await paste("Transcript", false) == .sent)
    #expect(environment.sentTo == [42])
}

@Test @MainActor func appOrFieldChangesPreventPaste() async {
    let environment = PasteEnvironment()
    let paste = environment.paster().prepare()
    environment.target = .init(pid: 43, element: AXUIElementCreateApplication(43))
    #expect(await paste("Transcript", false) == .targetChanged)
    environment.target = .init(pid: 42, element: AXUIElementCreateSystemWide())
    #expect(await paste("Transcript", false) == .targetChanged)
    environment.target = .init(pid: 42, element: nil)
    #expect(await paste("Transcript", false) == .targetChanged)
    environment.target = nil
    #expect(await paste("Transcript", false) == .targetChanged)
    #expect(environment.sentTo.isEmpty)
}

@Test @MainActor func editorsWithoutAccessibilityElementsStillGetBestEffortPaste() async {
    let environment = PasteEnvironment()
    environment.target = .init(pid: 42, element: nil)
    let paste = environment.paster().prepare()
    #expect(await paste("Transcript", false) == .sent)
    environment.target = .init(pid: 43, element: nil)
    #expect(await paste("Transcript", false) == .targetChanged)
    #expect(environment.sentTo == [42])
}

@Test @MainActor func missingOrRevokedAccessibilityNeverPostsKeys() async {
    let environment = PasteEnvironment()
    let previouslyAllowed = environment.paster().prepare()
    environment.allowed = false
    #expect(await previouslyAllowed("Transcript", false) == .accessibilityRequired)
    let denied = environment.paster().prepare()
    #expect(await denied("Transcript", false) == .accessibilityRequired)
    environment.allowed = true
    #expect(await denied("Transcript", false) == .accessibilityRequired)
    #expect(environment.sentTo.isEmpty)
}

@Test @MainActor func missingInitialTargetDoesNotPasteIntoALaterApp() async {
    let environment = PasteEnvironment()
    environment.target = nil
    let paste = environment.paster().prepare()
    environment.target = .init(pid: 42, element: nil)
    #expect(await paste("Transcript", false) == .targetUnavailable)
    #expect(environment.sentTo.isEmpty)
}

@Test @MainActor func heldModifiersPreventAlteredPasteShortcuts() async {
    let environment = PasteEnvironment()
    let paste = environment.paster().prepare()
    for flag: CGEventFlags in [.maskCommand, .maskControl, .maskAlternate, .maskShift, .maskSecondaryFn] {
        environment.flags = flag
        #expect(await paste("Transcript", false) == .modifiersPressed)
    }
    #expect(environment.sentTo.isEmpty)
    environment.flags = .maskAlphaShift // Caps Lock does not alter ⌘V.
    #expect(await paste("Transcript", false) == .sent)
}

@Test @MainActor func eventFailureIsReportedForManualRecovery() async {
    let environment = PasteEnvironment()
    environment.canPost = false
    #expect(await environment.paster().prepare()("Transcript", false) == .failed)
}

@Test @MainActor func temporaryPasteRestoresEveryClipboardItemAndRepresentation() async throws {
    let board = NSPasteboard.withUniqueName()
    defer { board.releaseGlobally() }
    let text = NSPasteboardItem(), image = NSPasteboardItem()
    let richText = Data(#"{\rtf1 Original formatted text}"#.utf8)
    let imageBytes = Data([137, 80, 78, 71, 1, 2, 3])
    text.setString("Original text", forType: .string)
    text.setData(richText, forType: .rtf)
    image.setData(imageBytes, forType: .png)
    image.setString("file:///tmp/example.png", forType: .fileURL)
    #expect(board.writeObjects([text, image]))
    let environment = PasteEnvironment()
    let transcript = "Hello 👋\n第二行\tend"
    environment.onPost = {
        #expect(board.string(forType: .string) == transcript)
        #expect(board.types?.contains(.init("org.nspasteboard.TransientType")) == true)
        #expect(board.types?.contains(.init("org.nspasteboard.AutoGeneratedType")) == true)
    }
    var waited = false
    let paste = environment.paster(pasteboard: board, waitForPaste: {
        await Task.yield()
        #expect(board.string(forType: .string) == transcript)
        waited = true
    }).prepare()
    #expect(await paste(transcript, true) == .sent)
    let restored = try #require(board.pasteboardItems)
    #expect(waited && environment.sentTo == [42])
    #expect(restored.count == 2)
    #expect(restored[0].string(forType: .string) == "Original text")
    #expect(restored[0].data(forType: .rtf) == richText)
    #expect(restored[1].data(forType: .png) == imageBytes)
    #expect(restored[1].string(forType: .fileURL) == "file:///tmp/example.png")
    #expect(board.types?.contains(.init("org.nspasteboard.TransientType")) != true)
}

@Test @MainActor func temporaryPasteRestoresEmptyClipboardAndRestoresAfterPostFailure() async {
    let board = NSPasteboard.withUniqueName()
    defer { board.releaseGlobally() }
    let environment = PasteEnvironment()
    #expect(await environment.paster(pasteboard: board).prepare()("Transcript", true) == .sent)
    #expect(board.pasteboardItems?.isEmpty != false)

    board.setString("Keep this", forType: .string)
    environment.canPost = false
    let paste = environment.paster(pasteboard: board, waitForPaste: {
        Issue.record("Failed event delivery must restore immediately")
    }).prepare()
    #expect(await paste("Transcript", true) == .failed)
    #expect(board.string(forType: .string) == "Keep this")
}

@Test @MainActor func temporaryPasteDoesNotOverwriteNewerClipboardContents() async {
    let board = NSPasteboard.withUniqueName()
    defer { board.releaseGlobally() }
    board.setString("Old clipboard", forType: .string)
    let environment = PasteEnvironment()
    let paste = environment.paster(pasteboard: board, waitForPaste: {
        board.clearContents()
        board.setString("Copied while pasting", forType: .string)
    }).prepare()
    #expect(await paste("Transcript", true) == .sent)
    #expect(board.string(forType: .string) == "Copied while pasting")
}

@Test @MainActor func temporaryPasteRestoresClipboardEvenWhenCancelledAfterPosting() async throws {
    let board = NSPasteboard.withUniqueName()
    defer { board.releaseGlobally() }
    board.setString("Keep this", forType: .string)
    let environment = PasteEnvironment()
    var resume: CheckedContinuation<Void, Never>?
    let paste = environment.paster(pasteboard: board, waitForPaste: {
        await withCheckedContinuation { resume = $0 }
    }).prepare()
    let task = Task { await paste("Transcript", true) }
    while resume == nil { await Task.yield() }
    task.cancel()
    #expect(board.string(forType: .string) == "Transcript")
    resume?.resume()
    #expect(await task.value == .sent)
    #expect(board.string(forType: .string) == "Keep this")
}

@Test @MainActor func skippedTemporaryPasteNeverChangesClipboard() async {
    let board = NSPasteboard.withUniqueName()
    defer { board.releaseGlobally() }
    board.setString("Keep this", forType: .string)
    let originalChangeCount = board.changeCount
    let environment = PasteEnvironment()
    let paste = environment.paster(pasteboard: board).prepare()
    environment.allowed = false
    #expect(await paste("Transcript", true) == .accessibilityRequired)
    environment.allowed = true
    environment.flags = .maskCommand
    #expect(await paste("Transcript", true) == .modifiersPressed)
    environment.flags = []
    environment.target = nil
    #expect(await paste("Transcript", true) == .targetChanged)
    #expect(board.changeCount == originalChangeCount && environment.sentTo.isEmpty)
}

@Test @MainActor func normalPasteLeavesCopiedTranscriptOnClipboard() async {
    let board = NSPasteboard.withUniqueName()
    defer { board.releaseGlobally() }
    board.setString("Transcript", forType: .string)
    let originalChangeCount = board.changeCount
    let environment = PasteEnvironment()
    #expect(await environment.paster(pasteboard: board).prepare()("Transcript", false) == .sent)
    #expect(board.string(forType: .string) == "Transcript" && board.changeCount == originalChangeCount)
}

@MainActor private final class PinEnvironment {
    var allowed = true
    let field = AXUIElementCreateApplication(42)
    lazy var target: TranscriptPaster.Target? = .init(pid: 42, element: field)
    var accepting = true
    var running = true
    var exposed = 0
    var exposes = true
    var inserted: [String] = []
    var pasted = 0
    var onRetry: () -> Void = {}
    var windowField: AXUIElement?
    var writeResult: TranscriptInsertResult = .inserted
    var typed: [String] = []
    var focusable = true

    func paster() -> TranscriptPaster {
        TranscriptPaster(accessibilityGranted: { self.allowed }, focusedTarget: { self.target },
                         modifiers: { [] }, postPaste: { _ in self.pasted += 1; return true },
                         exposeAccessibility: { _ in self.exposed += 1; return self.exposes },
                         acceptsText: { element in
                             defer { self.onRetry() }
                             return self.accepting && CFEqual(element, self.field)
                         },
                         insertText: { text, _ in
                             if self.writeResult == .inserted { self.inserted.append(text) }
                             return self.writeResult
                         },
                         appName: { _ in self.running ? "T3 Code" : nil },
                         searchFocusedField: { _ in self.windowField },
                         characterCount: { _ in nil },
                         typeText: { text, _ in self.typed.append(text); return true },
                         focusField: { _ in self.focusable })
    }

    func pinned() async -> PinnedTranscriptDestination? {
        guard case .pinned(let destination) = await paster().pin(retryDelay: .zero) else { return nil }
        return destination
    }
}

@Test @MainActor func pinnedNativeFieldReceivesTextWithoutKeystrokes() async throws {
    let environment = PinEnvironment()
    environment.exposes = false
    let destination = try #require(await environment.pinned())
    #expect(destination.appName == "T3 Code")
    // The user moves on to another app; delivery still targets the pinned field.
    environment.target = .init(pid: 7, element: AXUIElementCreateApplication(7))
    #expect(await destination.insert("Hello there") == .inserted)
    #expect(environment.inserted == ["Hello there"] && environment.typed.isEmpty && environment.pasted == 0)
}

@Test @MainActor func pinnedChromiumFieldIsTypedIntoOnlyWhileFocused() async throws {
    let environment = PinEnvironment()
    let destination = try #require(await environment.pinned())
    // Lexical accepts an Accessibility write and drops it, so it is never tried.
    #expect(await destination.insert("Hello\nthere") == .inserted)
    #expect(environment.typed == ["Hello there"] && environment.inserted.isEmpty && environment.pasted == 0)
    environment.focusable = false
    #expect(await destination.insert("Stray letters") == .targetUnavailable)
    #expect(environment.typed.count == 1)
}

@Test @MainActor func pinWaitsForElectronToExposeItsFields() async throws {
    let environment = PinEnvironment()
    environment.accepting = false
    var checks = 0
    environment.onRetry = { checks += 1; if checks == 2 { environment.accepting = true } }
    #expect(await environment.pinned() != nil)
    #expect(environment.exposed == 1 && checks == 3)
}

@Test @MainActor func pinFindsTheFocusedFieldInTheWindowWhenTheAppReportsNone() async throws {
    let environment = PinEnvironment()
    environment.target = .init(pid: 42, element: nil)
    #expect(await environment.pinned() == nil)
    environment.windowField = environment.field
    let destination = try #require(await environment.pinned())
    #expect(await destination.insert("Hello") == .inserted && environment.typed == ["Hello"])
}

@Test @MainActor func pinFailsForUnwritableFieldsAndFocusChanges() async {
    let environment = PinEnvironment()
    environment.accepting = false
    #expect(await environment.pinned() == nil)
    environment.exposes = false
    var checks = 0
    environment.onRetry = { checks += 1 }
    #expect(await environment.pinned() == nil)
    #expect(checks == 1) // Native apps are not polled.
    environment.exposes = true
    environment.onRetry = { environment.target = .init(pid: 43, element: environment.field) }
    guard case .failed(let message) = await environment.paster().pin(retryDelay: .zero) else {
        Issue.record("A focus change must not pin another app"); return
    }
    #expect(message.contains("Focus changed"))
}

@Test @MainActor func pinRequiresAccessibilityAndAFocusedField() async {
    let environment = PinEnvironment()
    environment.allowed = false
    #expect(await environment.pinned() == nil)
    environment.allowed = true
    environment.target = nil
    #expect(await environment.pinned() == nil)
    #expect(environment.exposed == 0)
}

@Test @MainActor func pinnedDeliveryStopsWhenTheAppQuitsOrAccessibilityIsRevoked() async throws {
    let environment = PinEnvironment()
    let destination = try #require(await environment.pinned())
    environment.running = false
    #expect(await destination.insert("text") == .targetUnavailable)
    environment.running = true
    environment.allowed = false
    #expect(await destination.insert("text") == .accessibilityRequired)
    #expect(environment.inserted.isEmpty && environment.pasted == 0)
}

@Test @MainActor func refusedAccessibilityWritesAreTypedWithoutReturnOrTab() async throws {
    let environment = PinEnvironment()
    environment.exposes = false
    let destination = try #require(await environment.pinned())
    environment.writeResult = .rejected
    #expect(await destination.insert("First line\nSecond\tpart") == .inserted)
    #expect(environment.typed == ["First line Second part"] && environment.pasted == 0)
    // An accepted write is never typed again, even if its length is not reported.
    environment.writeResult = .inserted
    #expect(await destination.insert("Once") == .inserted)
    #expect(environment.typed.count == 1 && environment.inserted == ["Once"])
    environment.writeResult = .targetUnavailable
    #expect(await destination.insert("Gone") == .targetUnavailable)
    #expect(environment.typed.count == 1)
}
